site_name: Signature emails URCA
title: Signature emails URCA
description: Outil de génération de signature.
author: Brahim MACHKOURI  
baseurl: /signature-mail
timezone: Europe/Paris
# social links
#twitter_username: thesubmarine # DO NOT include the @ character, or else the build will fail!
github_username:  brahimmachkouri # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
show_tags: false # set to false to remove tags on the homepage
plugins:
  - jemoji
